Internal Server Error: /wx/login
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/views.py", line 18, in user_login
    get_data = json.loads(request.body)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[27/Sep/2018 18:06:28] "GET /wx/login HTTP/1.0" 500 78927
Not Found: /favicon.ico
[27/Sep/2018 18:06:29] "GET /favicon.ico HTTP/1.0" 404 2082
Performing system checks...

System check identified no issues (0 silenced).
September 27, 2018 - 17:58:44
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[27/Sep/2018 18:07:45] "GET /wx/login HTTP/1.0" 200 69
[27/Sep/2018 18:08:34] "GET /wx/login HTTP/1.0" 200 69
Not Found: /wx/log
[27/Sep/2018 18:08:38] "GET /wx/log HTTP/1.0" 404 2499
Internal Server Error: /wx/get_coupon
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/views.py", line 18, in user_login
    get_data = json.loads(request.body)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[27/Sep/2018 18:08:55] "GET /wx/get_coupon HTTP/1.0" 500 79587
[27/Sep/2018 21:40:29] "POST /wx/login HTTP/1.0" 200 69
Performing system checks...

System check identified no issues (0 silenced).
September 27, 2018 - 18:07:36
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /wx/login
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/views.py", line 18, in user_login
    get_data = json.loads(request.body)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[27/Sep/2018 21:53:51] "GET /wx/login HTTP/1.0" 500 79527
Not Found: /favicon.ico
[27/Sep/2018 21:53:51] "GET /favicon.ico HTTP/1.0" 404 2082
Not Found: /
[27/Sep/2018 22:15:34] "GET / HTTP/1.0" 404 2031
Not Found: /favicon.ico
[27/Sep/2018 22:15:35] "GET /favicon.ico HTTP/1.0" 404 2082
Not Found: /
[27/Sep/2018 22:39:24] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:27] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:29] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:30] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:32] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:37] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:38] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:40] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:41] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:42] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 22:39:44] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 23:06:02] "GET / HTTP/1.0" 404 2031
Not Found: /
[27/Sep/2018 23:06:27] "GET / HTTP/1.0" 404 2031
error code cant get openid
[27/Sep/2018 23:29:07] "POST /wx/login HTTP/1.0" 200 54
Performing system checks...

System check identified no issues (0 silenced).
September 27, 2018 - 21:52:48
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
error code cant get openid
[27/Sep/2018 23:58:43] "POST /wx/login HTTP/1.0" 200 54
Performing system checks...

System check identified no issues (0 silenced).
September 27, 2018 - 23:56:37
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
{'js_code': '033k2fYh2xnTSH0U3xZh29eiYh2k2fYj'}
https://api.weixin.qq.com/sns/jscode2session?appid=wxade43df560e74b6c&secret=4e62b8f7d726f5340c9d8137a20d243d&js_code=033k2fYh2xnTSH0U3xZh29eiYh2k2fYj&grant_type=authorization_code
{'errcode': 40125, 'errmsg': 'invalid appsecret, view more at http://t.cn/RAEkdVq, hints: [ req_id: yPnL.A0923hb36 ]'}
Performing system checks...

System check identified no issues (0 silenced).
September 28, 2018 - 00:00:21
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
September 28, 2018 - 00:11:03
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
error code cant get openid
[28/Sep/2018 00:29:24] "POST /wx/login HTTP/1.0" 200 170
Not Found: /robots.txt
[28/Sep/2018 02:03:09] "GET /robots.txt HTTP/1.0" 404 2079
Not Found: /
[28/Sep/2018 03:21:50] "GET / HTTP/1.0" 404 2031
Not Found: /rest/v1/AccountService/Accounts
[28/Sep/2018 07:34:44] "GET /rest/v1/AccountService/Accounts HTTP/1.0" 404 2142
Not Found: /
[28/Sep/2018 07:45:43] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:09] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:10] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:12] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:13] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:15] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:20] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:20] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:21] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:26] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:27] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 07:52:28] "GET / HTTP/1.0" 404 2031
Performing system checks...

System check identified no issues (0 silenced).
September 28, 2018 - 00:11:20
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[28/Sep/2018 12:28:53] "POST /wx/login HTTP/1.0" 200 97
已有用户
[28/Sep/2018 12:41:00] "POST /wx/login HTTP/1.0" 200 97
已有用户
[28/Sep/2018 12:42:17] "POST /wx/login HTTP/1.0" 200 97
已有用户
[28/Sep/2018 12:42:40] "POST /wx/login HTTP/1.0" 200 97
已有用户
[28/Sep/2018 12:57:25] "POST /wx/login HTTP/1.0" 200 97
Not Found: /robots.txt
[28/Sep/2018 16:11:18] "GET /robots.txt HTTP/1.0" 404 2079
Not Found: /
[28/Sep/2018 16:11:20] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 16:11:21] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 17:58:32] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 18:20:27] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 19:32:45] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 20:29:02] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 20:35:38] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 21:12:14] "GET / HTTP/1.0" 404 2031
Not Found: /
[28/Sep/2018 21:35:04] "GET / HTTP/1.0" 404 2031
Performing system checks...

System check identified no issues (0 silenced).
September 28, 2018 - 11:51:58
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /
[28/Sep/2018 23:17:22] "GET / HTTP/1.0" 404 2031
已有用户
[28/Sep/2018 23:27:29] "POST /wx/login HTTP/1.0" 200 97
[29/Sep/2018 00:43:38] "GET /wx/get_coupon HTTP/1.0" 200 69
已有用户
[29/Sep/2018 01:04:49] "POST /wx/login HTTP/1.0" 200 97
[29/Sep/2018 01:04:50] "GET /wx/get_coupon HTTP/1.0" 200 69
Not Found: /
[29/Sep/2018 01:41:20] "GET / HTTP/1.0" 404 2031
Not Found: /
[29/Sep/2018 02:27:56] "GET / HTTP/1.0" 404 2031
[29/Sep/2018 07:03:44] "HEAD /static/admin/images/login_logo.png HTTP/1.0" 404 1706
Not Found: /
[29/Sep/2018 09:33:20] "GET / HTTP/1.0" 404 2031
[29/Sep/2018 11:25:20] "GET /wx/get_coupon HTTP/1.0" 200 69
[29/Sep/2018 11:25:41] "GET /wx/get_coupon HTTP/1.0" 200 69
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '6.7%'}]}
System check identified no issues (0 silenced).
September 28, 2018 - 22:31:22
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 11:27:49
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[29/Sep/2018 11:28:00] "GET /wx/get_coupon HTTP/1.0" 200 69
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 11:27:56
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
None
None
{}
Internal Server Error: /wx/get_coupon
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 22, in _func
    logger.info(time)
NameError: name 'logger' is not defined
[29/Sep/2018 11:29:05] "GET /wx/get_coupon HTTP/1.0" 500 69161
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 11:28:45
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb4cdefdbf8>
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin_market/urls.py", line 20, in <module>
    path('wx/', include('weixin.urls')),
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/urls.py", line 2, in <module>
    from . import views
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/views.py", line 6, in <module>
    from .login_interface.login_operation import write_login_header, generate_header_value , check_header ,get_id_by_openid
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 6, in <module>
    from weixin_market.config import *
ModuleNotFoundError: No module named 'weixin_market.config'
Performing system checks...

Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 11:31:07
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f375b725bf8>
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin_market/urls.py", line 20, in <module>
    path('wx/', include('weixin.urls')),
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/urls.py", line 2, in <module>
    from . import views
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/views.py", line 6, in <module>
    from .login_interface.login_operation import write_login_header, generate_header_value , check_header ,get_id_by_openid
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 6, in <module>
    import logger
ModuleNotFoundError: No module named 'logger'
Performing system checks...

Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 11:31:46
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[29/Sep/2018 11:32:25] "GET /wx/get_coupon HTTP/1.0" 200 69
[29/Sep/2018 12:37:00] "GET /wx/get_coupon HTTP/1.0" 200 69
已有用户
[29/Sep/2018 12:39:16] "POST /wx/login HTTP/1.0" 200 97
Internal Server Error: /wx/get_coupon
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view weixin.login_interface.login_operation._func didn't return an HttpResponse object. It returned None instead.
[29/Sep/2018 12:39:18] "GET /wx/get_coupon HTTP/1.0" 500 55024
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 12:20:05
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
已有用户
[29/Sep/2018 12:45:14] "POST /wx/login HTTP/1.0" 200 97
[29/Sep/2018 12:45:15] "GET /wx/get_coupon HTTP/1.0" 200 176
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 12:43:46
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /wx/login
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/views.py", line 20, in user_login
    get_data = json.loads(request.body)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[29/Sep/2018 14:22:54] "GET /wx/login HTTP/1.0" 500 79522
Not Found: /favicon.ico
[29/Sep/2018 14:22:55] "GET /favicon.ico HTTP/1.0" 404 2082
Not Found: /
[29/Sep/2018 18:05:38] "GET / HTTP/1.0" 404 2031
[29/Sep/2018 18:24:03] "HEAD /static/admin/images/login_logo.png HTTP/1.0" 404 1706
Not Found: /
[29/Sep/2018 19:01:00] "GET / HTTP/1.0" 404 2031
Not Found: /
[29/Sep/2018 20:13:58] "GET / HTTP/1.0" 404 2031
Not Found: /robots.txt
[29/Sep/2018 20:14:21] "GET /robots.txt HTTP/1.0" 404 2079
Not Found: /sitemap.xml
[29/Sep/2018 20:14:23] "GET /sitemap.xml HTTP/1.0" 404 2082
Not Found: /.well-known/security.txt
[29/Sep/2018 20:14:26] "GET /.well-known/security.txt HTTP/1.0" 404 2121
Not Found: /favicon.ico
[29/Sep/2018 20:14:41] "GET /favicon.ico HTTP/1.0" 404 2082
Not Found: /
[29/Sep/2018 20:49:24] "GET / HTTP/1.0" 404 2031
Not Found: /
[29/Sep/2018 22:19:43] "GET / HTTP/1.0" 404 2031
Not Found: /user/register
[30/Sep/2018 00:45:14] "GET /user/register?element_parents=account/mail/%23value&ajax_form=1&_wrapper_format=drupal_aja HTTP/1.0" 404 2173
[30/Sep/2018 01:15:29] "GET /wx/get_coupon HTTP/1.0" 200 69
已有用户
[30/Sep/2018 01:15:45] "POST /wx/login HTTP/1.0" 200 97
[30/Sep/2018 01:15:45] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:20:50] "GET /wx/get_coupon HTTP/1.0" 200 69
已有用户
[30/Sep/2018 01:21:17] "POST /wx/login HTTP/1.0" 200 97
[30/Sep/2018 01:21:18] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:21:28] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:24:18] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:26:47] "GET /wx/get_coupon HTTP/1.0" 200 69
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '7.8%'}]}
System check identified no issues (0 silenced).
September 29, 2018 - 12:48:56
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 01:29:23] "GET /wx/get_coupon HTTP/1.0" 200 176
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:29:06
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 01:30:34] "GET /wx/get_coupon HTTP/1.0" 200 69
Not Found: /
[30/Sep/2018 01:31:11] "GET / HTTP/1.0" 404 2031
[30/Sep/2018 01:34:02] "GET /wx/get_coupon HTTP/1.0" 200 69
Not Found: /wx/get_all_goods
[30/Sep/2018 01:34:02] "GET /wx/get_all_goods HTTP/1.0" 404 2529
[30/Sep/2018 01:34:16] "GET /wx/get_coupon HTTP/1.0" 200 69
Not Found: /wx/get_all_goods
[30/Sep/2018 01:34:16] "GET /wx/get_all_goods HTTP/1.0" 404 2529
已有用户
[30/Sep/2018 01:34:59] "POST /wx/login HTTP/1.0" 200 97
Not Found: /wx/get_all_goods
[30/Sep/2018 01:34:59] "GET /wx/get_all_goods HTTP/1.0" 404 2529
[30/Sep/2018 01:34:59] "GET /wx/get_coupon HTTP/1.0" 200 176
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:30:10
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:36:58
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 01:37:38] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:37:38] "GET /wx/get_all_goods HTTP/1.0" 200 561
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:37:32
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 01:38:13] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:38:13] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:38:56] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:38:56] "GET /wx/get_all_goods HTTP/1.0" 200 561
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:38:12
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 01:40:39] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:40:39] "GET /wx/get_coupon HTTP/1.0" 200 176
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:39:42
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 01:43:09] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:43:09] "GET /wx/get_coupon HTTP/1.0" 200 176
Not Found: /robots.txt
[30/Sep/2018 01:44:29] "GET /robots.txt HTTP/1.0" 404 2079
Not Found: /
[30/Sep/2018 01:44:32] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 01:44:33] "GET / HTTP/1.0" 404 2031
[30/Sep/2018 01:45:51] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:45:51] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:46:01] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:46:01] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:46:39] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:46:39] "GET /wx/get_all_goods HTTP/1.0" 200 561
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:42:08
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
已有用户
[30/Sep/2018 01:49:11] "POST /wx/login HTTP/1.0" 200 97
[30/Sep/2018 01:49:12] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:49:12] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:50:53] "POST /wx/login HTTP/1.0" 200 97
已有用户
[30/Sep/2018 01:50:53] "POST /wx/login HTTP/1.0" 200 97
[30/Sep/2018 01:50:54] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:50:54] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:51:32] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:51:32] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:51:47] "POST /wx/login HTTP/1.0" 200 97
[30/Sep/2018 01:51:48] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:51:48] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:52:32] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:52:32] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 01:53:19] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 01:53:19] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 02:02:42] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 02:02:42] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 02:02:55] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 02:02:55] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 02:03:05] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 02:03:05] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 02:05:01] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 02:05:01] "GET /wx/get_all_goods HTTP/1.0" 200 561
Not Found: /
[30/Sep/2018 03:06:59] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 04:49:06] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 08:45:57] "GET / HTTP/1.0" 404 2031
[30/Sep/2018 09:09:04] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 09:09:04] "GET /wx/get_coupon HTTP/1.0" 200 176
Not Found: /
[30/Sep/2018 09:37:52] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 09:37:52] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 09:37:52] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 09:38:22] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 09:38:30] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 09:38:30] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 09:50:48] "GET / HTTP/1.0" 404 2031
已有用户
[30/Sep/2018 10:26:16] "POST /wx/login HTTP/1.0" 200 97
[30/Sep/2018 10:26:20] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 10:26:20] "GET /wx/get_all_goods HTTP/1.0" 200 561
[30/Sep/2018 10:33:51] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 10:33:51] "GET /wx/get_all_goods HTTP/1.0" 200 561
Not Found: /wx/payOrder
[30/Sep/2018 10:33:55] "POST /wx/payOrder HTTP/1.0" 404 2700
[30/Sep/2018 10:44:21] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 10:44:21] "GET /wx/get_all_goods HTTP/1.0" 200 561
Not Found: /wx/payOrder
[30/Sep/2018 10:44:26] "POST /wx/payOrder HTTP/1.0" 404 2700
Not Found: /wx/payOrder
[30/Sep/2018 10:51:29] "POST /wx/payOrder HTTP/1.0" 404 2700
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 01:46:54
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 11:00:03
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /wx/payOrder
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: payOrder() missing 1 required positional argument: 'user_id'
[30/Sep/2018 11:01:02] "POST /wx/payOrder HTTP/1.0" 500 59773
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 11:00:55
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 11:02:18] "POST /wx/payOrder HTTP/1.0" 200 45
Performing system checks...

{'succ': '1', 'mess': '查询成功', 'data': [{'courseName': '现代市场营销素质与能力提升', 'planProgress': '8.9%'}]}
System check identified no issues (0 silenced).
September 30, 2018 - 11:02:16
Django version 2.1, using settings 'weixin_market.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Sep/2018 11:02:53] "POST /wx/payOrder HTTP/1.0" 200 45
[30/Sep/2018 11:02:57] "POST /wx/payOrder HTTP/1.0" 200 45
Internal Server Error: /wx/get_all_goods
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 18, in _func
    openid = header["HTTP_OPENID"]  #获取前端的openid
KeyError: 'HTTP_OPENID'
[30/Sep/2018 15:59:58] "GET /wx/get_all_goods HTTP/1.0" 500 68642
[30/Sep/2018 16:01:07] "GET /wx/get_coupon HTTP/1.0" 200 69
[30/Sep/2018 16:01:07] "GET /wx/get_all_goods HTTP/1.0" 200 69
[30/Sep/2018 16:01:28] "POST /wx/payOrder HTTP/1.0" 200 208
[30/Sep/2018 16:04:17] "POST /wx/payOrder HTTP/1.0" 200 208
[30/Sep/2018 16:04:52] "POST /wx/payOrder HTTP/1.0" 200 208
Internal Server Error: /wx/get_all_goods
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 18, in _func
    openid = header["HTTP_OPENID"]  #获取前端的openid
KeyError: 'HTTP_OPENID'
[30/Sep/2018 16:15:40] "GET /wx/get_all_goods HTTP/1.0" 500 68042
Internal Server Error: /wx/get_all_goods
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 19, in _func
    time = header["HTTP_TIME"]
KeyError: 'HTTP_TIME'
[30/Sep/2018 16:16:32] "GET /wx/get_all_goods HTTP/1.0" 500 68400
[30/Sep/2018 16:17:45] "GET /wx/get_all_goods HTTP/1.0" 200 737
[30/Sep/2018 16:17:45] "GET /wx/get_coupon HTTP/1.0" 200 176
Internal Server Error: /wx/get_all_goods
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/weixin_project/code/weixin_market/weixin/login_interface/login_operation.py", line 19, in _func
    time = header["HTTP_TIME"]
KeyError: 'HTTP_TIME'
[30/Sep/2018 16:21:09] "GET /wx/get_all_goods HTTP/1.0" 500 68398
[30/Sep/2018 16:23:54] "GET /wx/get_all_goods HTTP/1.0" 200 69
[30/Sep/2018 16:24:15] "GET /wx/get_all_goods HTTP/1.0" 200 69
[30/Sep/2018 16:25:34] "GET /wx/get_all_goods HTTP/1.0" 200 737
[30/Sep/2018 16:30:15] "GET /wx/get_all_goods HTTP/1.0" 200 737
[30/Sep/2018 16:30:15] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 16:30:40] "GET /wx/get_all_goods HTTP/1.0" 200 737
[30/Sep/2018 16:30:40] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 16:34:25] "GET /wx/get_class HTTP/1.0" 200 96
Not Found: /
[30/Sep/2018 17:22:09] "GET / HTTP/1.0" 404 2031
[30/Sep/2018 18:53:52] "GET /wx/get_coupon HTTP/1.0" 200 69
[30/Sep/2018 18:53:52] "GET /wx/get_all_goods HTTP/1.0" 200 69
[30/Sep/2018 19:41:13] "GET /wx/get_all_goods HTTP/1.0" 200 737
[30/Sep/2018 19:41:13] "GET /wx/get_coupon HTTP/1.0" 200 176
[30/Sep/2018 19:41:24] "POST /wx/payOrder HTTP/1.0" 200 208
Not Found: /otsmobile/app/mgs/mgw.htm
[30/Sep/2018 20:24:27] "GET /otsmobile/app/mgs/mgw.htm?operationType=com.cars.otsmobile.queryLeftTicketA&requestData=%5B%7B%22train_date%22%3A%2220181010%22%2C%22purpose_codes%22%3A%2200%22%2C%22from_station%22%3A%22PIJ%22%2C%22to_station%22%3A%22POJ%22%2C%22station_train_code%22%3A%22%22%2C%22start_time_begin%22%3A%220000%22%2C%22start_time_end%22%3A%222400%22%2C%22train_headers%22%3A%22QB%23%22%2C%22train_flag%22%3A%22%22%2C%22seat_type%22%3A%22%22%2C%22seatBack_Type%22%3A%22%22%2C%22ticket_num%22%3A%22%22%2C%22dfpStr%22%3A%22%22%2C%22baseDTO%22%3A%7B%22check_code%22%3A%22a8b5fdee33a609185ab6fafea27feefc%22%2C%22device_no%22%3A%22a863773724baecb4%22%2C%22mobile_no%22%3A%22%22%2C%22os_type%22%3A%22a%22%2C%22time_str%22%3A%2220180930202427%22%2C%22user_name%22%3A%22%22%2C%22version_no%22%3A%224.0.0.07121250%22%7D%7D%5D&ts=1538310267111&sign= HTTP/1.0" 404 2935
Not Found: /
[30/Sep/2018 21:37:42] "GET / HTTP/1.0" 404 2031
Not Found: /
[30/Sep/2018 23:10:15] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 00:00:44] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 01:58:09] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 01:58:15] "OPTIONS / HTTP/1.0" 404 2035
Not Found: /nice ports,/Trinity.txt.bak
[01/Oct/2018 01:58:18] "GET /nice%20ports,/Trinity.txt.bak HTTP/1.0" 404 2132
Not Found: /robots.txt
[01/Oct/2018 02:53:56] "GET /robots.txt HTTP/1.0" 404 2079
Not Found: /
[01/Oct/2018 02:53:58] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 02:53:59] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 03:44:47] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 05:31:18] "GET / HTTP/1.0" 404 2031
[01/Oct/2018 12:36:58] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 12:36:58] "GET /wx/get_coupon HTTP/1.0" 200 69
[01/Oct/2018 12:37:03] "POST /wx/payOrder HTTP/1.0" 200 208
[01/Oct/2018 12:49:47] "POST /wx/login HTTP/1.0" 200 97
[01/Oct/2018 12:49:48] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 12:49:48] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 12:50:41] "POST /wx/login HTTP/1.0" 200 97
[01/Oct/2018 12:50:56] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 12:50:56] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 13:05:14] "GET /wx/get_coupon HTTP/1.0" 200 69
[01/Oct/2018 13:05:14] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 13:05:20] "POST /wx/payOrder HTTP/1.0" 200 208
[01/Oct/2018 13:27:51] "GET /wx/get_coupon HTTP/1.0" 200 69
[01/Oct/2018 13:27:51] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 13:29:37] "POST /wx/payOrder HTTP/1.0" 200 208
Not Found: /
[01/Oct/2018 13:43:47] "GET / HTTP/1.0" 404 2031
[01/Oct/2018 14:28:11] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:29:27] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:29:27] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:29:49] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:29:49] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:30:32] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:30:32] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:31:06] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 14:31:06] "GET /wx/get_coupon HTTP/1.0" 200 69
[01/Oct/2018 14:31:29] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:31:29] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:32:47] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:32:47] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:33:45] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:33:45] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:34:33] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:34:33] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:34:46] "POST /wx/payOrder HTTP/1.0" 200 208
[01/Oct/2018 14:36:26] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:36:26] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:38:23] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 14:38:23] "GET /wx/get_coupon HTTP/1.0" 200 69
[01/Oct/2018 14:39:03] "GET /wx/get_coupon HTTP/1.0" 200 69
[01/Oct/2018 14:39:04] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 14:42:57] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:43:02] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:43:26] "GET /wx/get_all_goods HTTP/1.0" 200 737
[01/Oct/2018 14:43:26] "GET /wx/get_coupon HTTP/1.0" 200 176
[01/Oct/2018 14:48:26] "GET /wx/get_all_goods HTTP/1.0" 200 69
[01/Oct/2018 14:48:26] "GET /wx/get_coupon HTTP/1.0" 200 69
Not Found: /robots.txt
[01/Oct/2018 16:13:36] "GET /robots.txt HTTP/1.0" 404 2079
Not Found: /
[01/Oct/2018 16:13:38] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 16:13:39] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 21:37:18] "GET / HTTP/1.0" 404 2031
Not Found: /
[01/Oct/2018 22:49:03] "GET / HTTP/1.0" 404 2031
